name: Delete PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete preview directory
        run: |
          PREVIEW_PATH="pr-${{ github.event.number }}"
          if [ -d "$PREVIEW_PATH" ]; then
            rm -rf "$PREVIEW_PATH"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Delete preview for PR #${{ github.event.number }}" || echo "No changes to commit"
            git push origin gh-pages
            echo "Preview deleted: $PREVIEW_PATH"
          else
            echo "Preview directory not found: $PREVIEW_PATH"
          fi