name: Delete PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview screenshots
        run: |
          # Find and delete releases with screenshots for this PR
          PR_NUM="${{ github.event.number }}"
          echo "Looking for screenshot releases for PR #$PR_NUM"
          
          # Get all releases and filter for screenshot releases for this PR
          gh release list --json tagName,name | jq -r ".[] | select(.tagName | startswith(\"screenshot-pr-$PR_NUM-\")) | .tagName" | while read tag; do
            if [ -n "$tag" ]; then
              echo "Deleting release: $tag"
              gh release delete "$tag" --yes || echo "Failed to delete release $tag"
            fi
          done
          
          echo "Screenshot cleanup completed for PR #$PR_NUM"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}